const mongoose = require("mongoose");

const planSchema = new mongoose.Schema(
  {
    // ─── Library Reference ────────────────────────────────────────────────────
    // Denormalized for performance
    // Avoids extra DB query when fetching all plans of library
    libraryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Library",
      required: [true, "Library reference is required"],
    },

    // ─── TimeSlot Reference ───────────────────────────────────────────────────
    // Which time slot this plan is for
    // e.g. Morning slot / Evening slot / Night slot
    timeSlotId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TimeSlot",
      required: [true, "Time slot reference is required"],
    },

    // ─── Plan Name ────────────────────────────────────────────────────────────
    // AUTO GENERATED by system — not entered by owner
    // Format → "SeatType - SlotName"
    // e.g. "General - Morning", "VIP - Night Shift", "Cabin - 24 Hours"
    // Makes plans easily identifiable on dashboard
    name: {
      type: String,
      required: [true, "Plan name is required"],
      trim: true,
      minLength: [2, "Plan name must be at least 2 characters"],
      maxLength: [100, "Plan name cannot exceed 100 characters"],
    },

    // ─── Seat Type ────────────────────────────────────────────────────────────
    // Which seat category this plan applies to
    // NOT one specific seat — applies to ALL seats of this type
    //
    // Real example:
    // Plan "General - Morning" → applies to A1, A2, A3... ALL general seats
    // Student books A1(general) + Morning → system finds this plan → ₹120
    // Student books A2(general) + Morning → same plan → ₹120
    seatType: {
      type: String,
      required: [true, "Seat type is required"],
      enum: {
        values: ["general", "vip", "window", "cabin"],
        message: "{VALUE} is not a valid seat type",
      },
    },

    // ─── Duration Type ────────────────────────────────────────────────────────
    // Monthly only for now
    // Daily/Weekly → after handover (noted in improvements list)
    durationType: {
      type: String,
      required: [true, "Duration type is required"],
      enum: {
        values: ["monthly"],
        message: "{VALUE} is not a valid duration type",
        // daily, weekly → added after handover
      },
      default: "monthly",
    },

    // ─── Calculated Price ─────────────────────────────────────────────────────
    // AUTO calculated by system — never entered manually
    // Formula → library.hourlyRates[seatType] × (timeSlot.durationMinutes / 60)
    //
    // Examples:
    // General(₹20) + Morning(6hrs)  → 20 × 6  = ₹120/month
    // VIP(₹30)     + Morning(6hrs)  → 30 × 6  = ₹180/month
    // General(₹20) + Night(7hrs)    → 20 × 7  = ₹140/month
    // Cabin(₹40)   + 24hr(24hrs)    → 40 × 24 = ₹960/month
    //
    // When owner updates hourlyRate:
    // → System finds all plans for that seatType
    // → Recalculates calculatedPrice for each
    // → Existing bookings untouched (price snapshot on Booking)
    // → New bookings use updated price
    calculatedPrice: {
      type: Number,
      required: [true, "Calculated price is required"],
      min: [1, "Calculated price must be at least ₹1"],
    },

    // ─── Plan Status ──────────────────────────────────────────────────────────
    isActive: {
      type: Boolean,
      default: true,
      // true  → plan available for new bookings
      // false → plan hidden, no new bookings allowed
      //         existing bookings on this plan NOT affected
    },

    // ─── Status Audit Trail ───────────────────────────────────────────────────
    // Tracks who changed plan status and when
    statusUpdatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    statusUpdatedAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true },
);

// ─── Compound Unique Index ────────────────────────────────────────────────────
// Same slot + seat type cannot exist twice in same library
// ONE plan per slot per seat type per library
//
// Why ONE plan is enough?
// Plan is a PRICE RULE — not a booking
// "General + Morning = ₹120" applies to ALL general seats
// No need for multiple plans for same combination
//
// Library A → Morning + General ✅
// Library A → Morning + General again ❌ blocked
// Library A → Morning + VIP ✅ (different seat type)
// Library B → Morning + General ✅ (different library)
planSchema.index(
  { libraryId: 1, timeSlotId: 1, seatType: 1 },
  { unique: true },
);

const Plan = mongoose.model("Plan", planSchema);
module.exports = Plan;
